### PR TITLE
Groceries

### PR DESCRIPTION
**Pull request by cedaley**
Steven and Christina updated the database with adding groceries feature

### CODE REVIEW

**Comment by shelbychen97** [comment]
LGTM

**Comment by shelbychen97** [comment]
Database looks much better. Organization looks better with all the roommates in difference sections. 10/10 job

**Comment by abaile06** [comment]
When you are ready you can delete the grocery branch.

**Comment by gabbynobili** [comment]
Other than maybe removing a few comments looks great!

**Pull request merged**
